// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qlewmobggivoejnowsxx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFsZXdtb2JnZ2l2b2Vqbm93c3h4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg3MTc0NDUsImV4cCI6MjA2NDI5MzQ0NX0.ihhNDA24xuBgBNhqM1q_xcMasCN4PmENx9DSeuXkdGI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);